"""baseline schema

Revision ID: 0ff9baa6bb2e
Revises: 
Create Date: 2026-07-14 16:14:13.651448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ff9baa6bb2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('org_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('org_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_reg_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manager_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manager_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caregivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregivers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_caregivers_phone_hash'), ['phone_hash'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_phone_hash'), ['phone_hash'], unique=False)

    op.create_table('care_level_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cognitive_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobility_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vision_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medication_awareness', sa.Boolean(), nullable=False),
    sa.Column('medication_willingness', sa.Boolean(), nullable=False),
    sa.Column('care_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregiver_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('inviter_caregiver_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_caregiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_caregiver_id'], ['caregivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dose_timing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caregiver_alert', sa.Boolean(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('care_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('all_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('guide_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('medication_guide', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lifestyle_guide', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_refs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed_by_caregiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drug_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drug_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('matched_drug_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_results')
    op.drop_table('medication_logs')
    op.drop_table('guide_results')
    op.drop_table('notification_settings')
    op.drop_table('medication_schedules')
    op.drop_table('medical_records')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))

    op.drop_table('invitations')
    op.drop_table('chat_messages')
    op.drop_table('caregiver_patients')
    op.drop_table('care_level_assessments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone_hash'))

    op.drop_table('patients')
    with op.batch_alter_table('caregivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caregivers_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_caregivers_email'))

    op.drop_table('caregivers')
    # ### end Alembic commands ###
