"""add prescription_date to medical_records

Revision ID: 16bd8c597acb
Revises: 152860ef0223
Create Date: 2026-07-23 11:31:11.031557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import

# revision identifiers, used by Alembic.
revision: str = '16bd8c597acb'
down_revision: Union[str, Sequence[str], None] = '152860ef0223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # [2026-07-23] caregiver_patients.status 콜레이션 변경은 autogenerate가 이번 변경과
    # 무관하게 잡아낸 기존 드리프트라 제외 — 이 마이그레이션은 prescription_date만 추가.
    op.add_column('medical_records', sa.Column('prescription_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'prescription_date')
    # ### end Alembic commands ###
