"""add_requested_by_role_to_caregiver_patients

Revision ID: 2ee38e8bc56e
Revises: d4e7b2c0f195
Create Date: 2026-07-20 16:06:37.073621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ee38e8bc56e'
down_revision: Union[str, Sequence[str], None] = 'd4e7b2c0f195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caregiver_patients', sa.Column('requested_by_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caregiver_patients', 'requested_by_role')
    # ### end Alembic commands ###
