"""add login lockout and account withdrawal fields

Revision ID: 38a30cdfa517
Revises: bcdbae97c089
Create Date: 2026-07-15 15:22:59.341128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = '38a30cdfa517'
down_revision: Union[str, Sequence[str], None] = 'bcdbae97c089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    # [2026-07-15 추가, PR #48 팀원 리뷰 반영] 이 마이그레이션 자체가 아직 실 DB에
    # 적용된 적이 없어(PR47 병합 대기 중) 새 리비전을 안 만들고 여기 직접 추가함.
    sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_code_hash'), ['code_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_subject_id'), ['subject_id'], unique=False)

    op.create_table('privacy_purge_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_purge_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_purge_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_purge_audits_subject_id'), ['subject_id'], unique=False)

    # [2026-07-15] autogenerate가 NOT NULL 컬럼(failed_login_attempts)에 기본값을 안
    # 채워서, 이미 행이 있는 테이블(caregivers/patients)에 적용하면 실패했을 것 —
    # server_default='0'으로 기존 행도 안전하게 채워지게 한다(bcdbae97c089와 동일 이유).
    with op.batch_alter_table('caregivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletion_scheduled_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletion_scheduled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('deletion_scheduled_at')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('caregivers', schema=None) as batch_op:
        batch_op.drop_column('deletion_scheduled_at')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('privacy_purge_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_purge_audits_subject_id'))

    op.drop_table('privacy_purge_audits')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_subject_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_code_hash'))

    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
