"""add schedule_caregiver_alerts table

Revision ID: 405992c665ba
Revises: bee05b2591cb
Create Date: 2026-07-24 11:45:29.470240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = '405992c665ba'
down_revision: Union[str, Sequence[str], None] = 'a313929ff868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_caregiver_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # [수동 추가] 같은 (schedule, caregiver) 조합이 중복 저장되는 걸 DB 차원에서 막는다.
    sa.UniqueConstraint('schedule_id', 'caregiver_id', name='uq_schedule_caregiver_alerts_schedule_caregiver'),
    )
    with op.batch_alter_table('schedule_caregiver_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_caregiver_alerts_caregiver_id'), ['caregiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_caregiver_alerts_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###

    # [수동 추가] 기존 데이터 백필 — caregiver_alert=True인 일정은 지금까지 "가장 먼저
    # 연결된 caregiver 1명"에게만 알림이 갔다(core/scheduler.py._recipients의 임의의
    # 단순화, models.py의 ScheduleCaregiverAlert 주석 참고). 이 마이그레이션 이후로는
    # "행이 없으면 연결된 caregiver 전원에게 발송"이 기본 동작이 되므로, 과거 일정도
    # 지금 시점 기준 연결된(해제되지 않은) caregiver 전원을 명시적으로 깔아둬 동작이
    # 갑자기 "아무에게도 안 감"으로 바뀌지 않게 한다 — 오히려 2번째·3번째 보호자도
    # 이제부터 받게 되어 원래 의도(라벨 그대로 "보호자에게도 알림")에 맞아진다.
    op.execute(
        sa.text(
            """
            INSERT INTO schedule_caregiver_alerts (schedule_id, caregiver_id)
            SELECT ms.id, cp.caregiver_id
            FROM medication_schedules ms
            JOIN caregiver_patients cp ON cp.patient_id = ms.patient_id
            WHERE ms.caregiver_alert = 1 AND cp.status != 'revoked'
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_caregiver_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_caregiver_alerts_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_caregiver_alerts_caregiver_id'))

    op.drop_table('schedule_caregiver_alerts')
    # ### end Alembic commands ###
