"""add_guide_cache_table

Revision ID: 66c32a201ba5
Revises: 2ee38e8bc56e
Create Date: 2026-07-20 14:51:15.768907

[2026-07-20 리베이스] PR #56도 같은 부모(9250cdf36945)에서 독립적으로 새 마이그레이션
체인을 만들어서 head가 두 개로 갈라지는 문제가 있었음 — 팀 논의에 따라 PR #56을 먼저
머지하기로 하고, 이 마이그레이션을 PR #56의 최종 head(2ee38e8bc56e) 위로 재배치함
(docs/Team Members' Notes/team-rules.md §12의 "머지 순서를 먼저 정하고 나중에 머지되는 쪽이 down_revision을
재배치" 규칙 적용). 이 리비전이 실 DB 어디에도 적용된 적이 없어 안전하게 재배치 가능.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66c32a201ba5'
down_revision: Union[str, Sequence[str], None] = '2ee38e8bc56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drug_names', sa.Text(), nullable=True),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guide_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_cache_cache_key'), 'guide_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_cache_cache_key'), table_name='guide_cache')
    op.drop_table('guide_cache')
    # ### end Alembic commands ###
