"""add_guide_cache_table

Revision ID: 66c32a201ba5
Revises: 9250cdf36945
Create Date: 2026-07-20 14:51:15.768907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66c32a201ba5'
down_revision: Union[str, Sequence[str], None] = '9250cdf36945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drug_names', sa.Text(), nullable=True),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guide_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_cache_cache_key'), 'guide_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_cache_cache_key'), table_name='guide_cache')
    op.drop_table('guide_cache')
    # ### end Alembic commands ###
