"""add meal time preferences to patients

Revision ID: 6abc05609053
Revises: ce29de6a55b2
Create Date: 2026-07-18 03:26:43.422596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = '6abc05609053'
down_revision: Union[str, Sequence[str], None] = 'ce29de6a55b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('breakfast_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patients', sa.Column('breakfast_regular', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('lunch_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patients', sa.Column('lunch_regular', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('dinner_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patients', sa.Column('dinner_regular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'dinner_regular')
    op.drop_column('patients', 'dinner_time')
    op.drop_column('patients', 'lunch_regular')
    op.drop_column('patients', 'lunch_time')
    op.drop_column('patients', 'breakfast_regular')
    op.drop_column('patients', 'breakfast_time')
    # ### end Alembic commands ###
