"""add patient_medications and medication_records, extend medication_schedules

Revision ID: 6ec828d72e5f
Revises: 0ff9baa6bb2e
Create Date: 2026-07-14 16:22:40.764819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = '6ec828d72e5f'
down_revision: Union[str, Sequence[str], None] = '0ff9baa6bb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('item_seq', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medication_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dosage_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dosage_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency_per_day', sa.Integer(), nullable=True),
    sa.Column('administration_route', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_medications_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_medications_item_seq'), ['item_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_medications_patient_id'), ['patient_id'], unique=False)

    op.create_table('medication_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_medication_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verification_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_records_patient_medication_id'), ['patient_medication_id'], unique=False)

    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_medication_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meal_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('days_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_medication_schedules_patient_medication_id'), ['patient_medication_id'], unique=False)
        # [2026-07-14] autogenerate가 이름 없는(None) FK 제약을 만들어서 SQLite batch 모드에서
        # "Constraint must have a name" 에러가 났다 — 직접 이름을 지정해서 고침.
        batch_op.create_foreign_key(
            'fk_medication_schedules_patient_medication_id', 'patient_medications', ['patient_medication_id'], ['id']
        )

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_email'))

    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medication_schedules_patient_medication_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medication_schedules_patient_medication_id'))
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('timezone')
        batch_op.drop_column('instructions')
        batch_op.drop_column('meal_relation')
        batch_op.drop_column('patient_medication_id')

    with op.batch_alter_table('medication_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_records_patient_medication_id'))

    op.drop_table('medication_records')
    with op.batch_alter_table('patient_medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_medications_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_medications_item_seq'))
        batch_op.drop_index(batch_op.f('ix_patient_medications_drug_id'))

    op.drop_table('patient_medications')
    # ### end Alembic commands ###
