"""add notification_logs table

Revision ID: 9250cdf36945
Revises: 38a30cdfa517
Create Date: 2026-07-19 02:44:34.408583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = '9250cdf36945'
down_revision: Union[str, Sequence[str], None] = '8064fd94bb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_slot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channels', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'due_date', 'time_slot', 'kind', name='uq_notification_instance')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_due_date'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
