"""add chatbot_name to notification_settings

Revision ID: bcdbae97c089
Revises: 6ec828d72e5f
Create Date: 2026-07-15 13:31:07.531726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import


# revision identifiers, used by Alembic.
revision: str = 'bcdbae97c089'
down_revision: Union[str, Sequence[str], None] = '6ec828d72e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # [2026-07-15] autogenerate가 NOT NULL 컬럼을 기본값 없이 추가하려고 해서, 이미 행이
    # 있는 notification_settings 테이블에 적용하면 실패한다 — server_default를 채워
    # 기존 행에도 안전하게 적용되게 한다(모델의 Field(default="약콩이")는 파이썬 레벨
    # 기본값이라 신규 INSERT에만 적용되고 ALTER TABLE엔 영향 없음).
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('chatbot_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='약콩이')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('chatbot_name')

    # ### end Alembic commands ###
