"""add revocation_notices table

Revision ID: bee05b2591cb
Revises: 993b8f6c21f6
Create Date: 2026-07-23 18:39:17.496547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import

# revision identifiers, used by Alembic.
revision: str = 'bee05b2591cb'
down_revision: Union[str, Sequence[str], None] = '993b8f6c21f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revocation_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counterpart_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revocation_notices')
    # ### end Alembic commands ###
