"""add revocation reason and timestamp, drop care level assessments

Revision ID: ca937bb9131f
Revises: dd2141948419
Create Date: 2026-07-23 16:05:42.800961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # [2026-07-14] SQLModel 커스텀 컬럼 타입(AutoString 등) autogenerate가 참조하므로 항상 import
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca937bb9131f'
down_revision: Union[str, Sequence[str], None] = 'dd2141948419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # [수동 제거] status 컬럼 type_ 변경(VARCHAR(50) → AutoString)은 실제 스키마 변경이
    # 아니라 SQLModel 타입 표현 방식 차이일 뿐이라 뺐다. ix_caregivers_email의 unique
    # 재적용도 뺐다 — 이건 PR#80(dd2141948419)이 이미 의도적으로 unique=False로 바꾼
    # 것을 이 브랜치가 아직 모델에 반영하지 않아 생긴 오탐(false diff)이다.
    op.drop_table('care_level_assessments')
    op.add_column('caregiver_patients', sa.Column('revocation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('caregiver_patients', sa.Column('revocation_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caregiver_patients', 'revocation_requested_at')
    op.drop_column('caregiver_patients', 'revocation_reason')
    op.create_table('care_level_assessments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cognitive_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('mobility_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('vision_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('medication_awareness', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('medication_willingness', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('care_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('evaluated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('care_level_assessments_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
